# Generated by Django 4.2.1 on 2023-05-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0003_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'Nepradėta'), (1, 'Vykdoma'), (2, 'Atlikta'), (3, 'Atšaukta')], default=0, help_text='Statusas', max_length=1, verbose_name='status'),
        ),
    ]
