# Generated by Django 4.2.1 on 2023-06-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0005_car_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='cover',
            new_name='pictures',
        ),
    ]
